<?php

namespace Templates;

use PiedWeb\Splates\Template\Template;
use PiedWeb\Splates\Template\TemplateClassInterface;

class Layout implements TemplateClassInterface
{
    /**
     * @param string[] $test323
     */
    public function display(Template $tpl, string $company, ?string $title = null): void
    { ?>
<html>
<head>
    <title><?=$tpl->e($title)?> | <?=$tpl->e($company)?></title>
</head>
<body>

<?=$tpl->section('content')?>

<?=$tpl->section('scripts')?>

</body>
</html>
<?php
    }

    /**
     * Autogenerated constructor.
     */
    public function __construct(public string $company, public ?string $title = null)
    {
    }
}
