<?php

namespace Templates;

use PiedWeb\Splates\Template\Template;
use PiedWeb\Splates\Template\TemplateClassInterface;
use PiedWeb\Splates\Template\TemplateEscape;
use PiedWeb\Splates\Template\TemplateFetch;

class Profile implements TemplateClassInterface
{

    public function display(Template $t, TemplateFetch $f, TemplateEscape $e, string $name): void { ?>
<?php $t->layout(new Layout('User Profile')) ?>
<?php // $this->layout('layout', ['title' => 'User Profile']) // this is working too and will get the example/templates/layout.php ?>

<h1>User Profile</h1>
<p>Hello, <?=$e($name)?>!</p>

<?= $f(new Sidebar()) ?>

<?php $t->push('scripts') ?>
    <script>
        // Some JavaScript
    </script>
<?php $t->end() ?>
<?php
    }
    /**
     * Autogenerated constructor.
     */
    public function __construct(public string $name)
    {
    }
}