<?php

declare(strict_types=1);

namespace PiedWeb\Splates;

use PhpParser\Comment\Doc;
use PhpParser\Modifiers;
use PhpParser\Node;
use PhpParser\Node\Name;
use PhpParser\Node\Param;
use PhpParser\Node\Stmt\Class_;
use PhpParser\Node\Stmt\ClassMethod;
use PiedWeb\Splates\Template\DoNotAddItInConstructorInterface;
use PiedWeb\Splates\Template\Template;
use PiedWeb\Splates\Template\TemplateClass;
use PiedWeb\Splates\Template\TemplateClassInterface;
use Rector\NodeTypeResolver\NodeTypeResolver;
use Rector\NodeTypeResolver\NodeTypeResolver\ParamTypeResolver;
use Rector\Rector\AbstractRector;
use Rector\StaticTypeMapper\ValueObject\Type\FullyQualifiedObjectType;
use Rector\ValueObject\MethodName;

/**
 * Rewrite
 * `final class SomeTemplate { public function display(string $name, Template $t): void { ... } }`
 * in
 * `final class SomeTemplate { public function display(string $name, Template $t): void { ... } public function __construct(public string $name) {} }`
 */
final class RectorizeTemplate extends AbstractRector
{
    public const array CLASS_TO_NOT_ADD_IN_CONSTRUCTOR = [
        Template::class,
        TemplateClass::class,
        DoNotAddItInConstructorInterface::class,
    ];

    public const array PARAMETER_NAMES_TO_NOT_ADD = ['f', 'e'];

    public function __construct(
        private readonly ParamTypeResolver $paramTypeResolver,
        protected NodeTypeResolver $nodeTypeResolver
    ) {
    }

    public function getNodeTypes(): array
    {
        return [Class_::class];
    }

    public function refactor(Node $node): ?Node
    {
        if (! $node instanceof Class_) {
            return null;
        }

        $implementedInterfaces = array_map(static fn (Name $interface): string => $interface->toString(), $node->implements);

        if (! \in_array(TemplateClassInterface::class, $implementedInterfaces, true)) {
            return null;
        }

        $displayMethod = $node->getMethod('display');
        if (! $displayMethod instanceof ClassMethod || $displayMethod->params === []) {
            $this->removeConstructor($node);

            return null;
        }

        $paramsForConstructor = [];
        $docBlockForConstructor = [];
        $methodDocBlock = $displayMethod->getDocComment()?->getText() ?? '';
        if (str_contains($methodDocBlock, '@phpstan-ignore-next-line')) {
            $docBlockForConstructor[] = '@phpstan-ignore-next-line';
        }

        foreach ($displayMethod->params as $parameter) {
            if (in_array($this->getName($parameter), self::PARAMETER_NAMES_TO_NOT_ADD, true)) {
                continue;
            }

            $paramType = $this->paramTypeResolver->resolve($parameter);
            if ($paramType instanceof FullyQualifiedObjectType && ! $this->mustAddObjectInConstructor($parameter, $paramType)) {
                continue;
            }

            $paramDocBlock = $this->getParameterDocblock($methodDocBlock, $this->getName($parameter));
            if ($paramDocBlock !== null) {
                $docBlockForConstructor[] = $paramDocBlock;
            }

            $cloneParameter = clone $parameter;
            $cloneParameter->flags = Modifiers::PUBLIC;

            $paramsForConstructor[] = $cloneParameter;
        }

        if ($paramsForConstructor === []) {
            $this->removeConstructor($node);

            return null;
        }

        $constructor = $node->getMethod(MethodName::CONSTRUCT);
        $docBlockConstructor = $constructor?->getDocComment();
        $dockBlockContent = trim("Autogenerated constructor.\n * \n * ".implode("\n * ", $docBlockForConstructor), "\n *");
        $newDocBlockConstructor = new Doc("/**\n * ".$dockBlockContent."\n */");
        if ($paramsForConstructor === $constructor?->params || $docBlockConstructor === $newDocBlockConstructor) { // TODO compare docblock
            return null;
        }

        $newConstructor = new ClassMethod(MethodName::CONSTRUCT, [
            'flags' => Modifiers::PUBLIC,
            'params' => $paramsForConstructor,
        ]);
        $newConstructor->setDocComment($newDocBlockConstructor);

        $this->removeConstructor($node);
        $node->stmts[] = $newConstructor;

        return $node;
    }

    private function removeConstructor(Class_ $class): void
    {
        foreach ($class->stmts as $key => $stmt) {
            if ($stmt instanceof ClassMethod && $stmt->name->toString() === MethodName::CONSTRUCT) {
                unset($class->stmts[$key]);

                break;
            }
        }
    }

    private function getParameterDocblock(?string $methodDocblock, string $parameterName): ?string
    {
        if ($methodDocblock === null) {
            return null;
        }

        $pattern = '/@param\s+[^$]*?\$' . $parameterName . '\b([^@]*)/';

        if (preg_match($pattern, $methodDocblock, $matches)) {
            return trim($matches[0], '*/ ' . "\n");
        }

        return null;
    }

    private function mustAddObjectInConstructor(Param $param, FullyQualifiedObjectType $paramType): bool
    {
        if (\in_array($paramType->getClassName(), self::CLASS_TO_NOT_ADD_IN_CONSTRUCTOR, true)) {
            return false;
        }

        foreach (self::CLASS_TO_NOT_ADD_IN_CONSTRUCTOR as $classToCheck) {
            if (is_subclass_of($paramType->getClassName(), $classToCheck)) {
                return false;
            }
        }

        return true;
    }
}
